# Generated by Django 4.2.7 on 2023-11-12 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='URL')),
                ('day', models.CharField(max_length=128, verbose_name='День')),
                ('subject', models.CharField(max_length=128, verbose_name='Предмет')),
                ('teacher', models.CharField(max_length=128, verbose_name='Преподаватель')),
                ('classroom', models.CharField(max_length=128, verbose_name='Аудитория')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='schedule.group')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
    ]
