# Generated by Django 4.2.7 on 2023-11-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='course',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='Курс'),
        ),
    ]
