# Generated by Django 4.2.7 on 2023-11-14 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_alter_group_options_remove_group_subgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Название')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Расписание')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='schedule.group')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
