# Generated by Django 4.2.7 on 2023-11-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_weekschedule_delete_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='content',
            field=models.TextField(blank=True, default='NullSchedule', verbose_name='Расписание'),
        ),
    ]
